<?php
/**
 * Created by PhpStorm.
 * User: RedZ
 * Date: 6/28/2018
 * Time: 5:28 PM
 */
require_once 'include/MVC/View/views/view.detail.php';

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
class Jump_QuoteViewDetail extends ViewDetail{
    public function preDisplay(){
		parent::preDisplay();
    	echo '<script type="text/javascript" src="custom/modules/jump_quote/js/custom.js"></script>';
    	
	}
    public function display()
    {
        parent::display(); // TODO: Change the autogenerated stub
        include('custom/include/templates/detail.template.php');
        // $template = new Sugar_Smarty();
        // $template->display('custom/include/tpls/view.sum.tpl');

    }

}