<?php
/**
 * Created by PhpStorm.
 * User: RedZ
 * Date: 7/4/2018
 * Time: 8:30 AM
 */
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

class Jump_sales_invoiceViewDetail extends ViewDetail{

    public function display()
    {
//        parent::display(); // TODO: Change the autogenerated stub

        include('custom/modules/jump_sales_invoice/tpls/view.detail.php');
    }
}