<?php
/**
 * Created by PhpStorm.
 * User: RedZ
 * Date: 7/2/2018
 * Time: 10:24 AM
 */

class Jump_sales_invoiceViewEdit extends ViewEdit{

    public function display()
    {
        parent::display(); // TODO: Change the autogenerated stub
    }
}